More example descriptions
threlte/threlte pull request #432
Opened 2023-06-23 15:57 UTC by midanosi

Had some more Example descriptions in progress!
Hope these aren't too verbose. I'm basically just going through the code to understand how it works, describing that, then in some cases highlighting the key bits from the code that are achieving what the example is doing.

And I'm sometimes pointing out some threejs or threlte functionality that a newbie (like myself) might not have grasped yet, but would otherwise be a blocker to understanding how a particular example works quickly.

Am in progress on fixing/updating the terrain-physics example and adding a description for that too, but will put that in a separate PR

2023-06-26 10:08 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/camera/pointer-lock-controls.mdx
> +2. > Pointer lock lets you access mouse events even when the cursor goes past the boundary of the browser or screen (from MDN doc)
Remove "(from MDN doc)"

2023-06-26 10:17 UTC, grischaerbe requested changes
Hey @midanosi, thanks so much for your contribution! It really helps understanding what's going on for beginners and advanced people alike.

I have some remarks, nothing special, otherwise LGTM 🚀 ❤️

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/camera/pointer-lock-controls.mdx
> +2. > Pointer lock lets you access mouse events even when the cursor goes past the boundary of the browser or screen (from MDN doc)
Remove "(from MDN doc)"

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/camera/pointer-lock-controls.mdx
> +To explain the 2nd point, find a threlte scene which uses OrbitControls for it's camera. Now click and drag the cursor left until you hit the edge of your screen.
Capital T for "Threlte"

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/camera/pointer-lock-controls.mdx
> +To explain the 2nd point, find a threlte scene which uses OrbitControls for it's camera. Now click and drag the cursor left until you hit the edge of your screen.
Mark "`OrbitControls`" as code with single backticks

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/geometry/terrain.mdx
> +Therefore we want to utilise 2D noise, and this example uses `createNoise2D` from npm package 'simplex-noise'.
"and this example uses the function `createNoise2D` from the package `simplex-noise`."

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/geometry/terrain.mdx
> +Aside: Why `i+=3`?
Cool addition! Make it a `<Tip type="tip">` ;)

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/geometry/terrain.mdx
> +6. This example intentionally used only part of the noise map (the middle 25%), in order to generate gentler terrain.
Make this a `<Tip type="tip">` too 👍

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/animation/transitions.mdx
> +GLTF is a comprehensive file format for 3D models, and it supports animations.
I think the correct capitalization is "glTF" although I didn't follow through with this in the rest of the codebase. Still, it's never too late to start!

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/animation/transitions.mdx
> +2. bind `gltf` to the GLTF component,
```md
bind `gltf` to the `<GLTF>` component:
```

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/animation/transitions.mdx
> +1. we extract the variables `gltf` and `actions`;
```md
Extract the variables `gltf` and `actions`:
```

2023-06-26 10:17 UTC, grischaerbe commented on apps/docs-next/src/content/learn/examples/animation/transitions.mdx
> +3. (tip) run `console.log(Object.entries($actions))` to see the available action strings, and the shape of the animation object. By doing this, you'll discover that this example is only using 3 of th
Also make this a `<Tip type="tip">` 👍

2023-06-27 14:11 UTC, midanosi commented
> Hey @midanosi, thanks so much for your contribution! It really helps understanding what's going on for beginners and advanced people alike.
> 
> I have some remarks, nothing special, otherwise LGTM 🚀 ❤️

Thank you for the compliment and the thorough feedback, have implemented and committed everything you suggested.
Two extra changes I made on top were startcasing 'threlte' to 'Threlte' in a few other places in the repo, and adding one more <Tip> in the terrain example. (using <Tip> is such a great shout)

2023-06-27 14:45 UTC, merged