Improve the README
threlte/threlte pull request #437
Opened 2023-06-27 21:46 UTC by ixxie

A new README for Threlte 6.

Animated banner scoped our because its hard to get it right.

2023-06-27 23:53 UTC, grischaerbe requested changes
Thanks again, looks and reads so much better than before ❤️ 

Found some smaller things here and there.
Also: Can you replace all links to "https://threlte.xyz" with "https://next.threlte.xyz" so it points to the next page? When merging to main (aka releasing T6) we can get rid of all "next" occurrences in one go 👍

2023-06-27 23:53 UTC, grischaerbe commented on README.md
> +Threlte's core **3D rendering** is powered by [Three.js](https://threejs.org/), but its also provides a **physics engine** through [Rapier](https://rapier.rs/) and an **animation engine** via [Theatr
Suggestion:

"Threlte's **3D rendering** is powered by [Three.js](https://threejs.org/), it provides a **physics engine** through [Rapier](https://rapier.rs/) and an **animation engine** via [Theatre.js](https://www.theatrejs.com/)."

2023-06-27 23:53 UTC, grischaerbe commented on README.md
> + - [Events](https://threlte.xyz/docs/learn/basics/events) lets you access state transformations in your scenes.
This sounds a bit odd, maybe "Events enabling robust and Svelte-native access to state transformations occurring within your scenes." or along these lines?

2023-06-27 23:53 UTC, grischaerbe commented on README.md
> + - [Interactivity](https://threlte.xyz/docs/reference/extras/interactivity) makes it easy to drive state with user actions on 3D objects.
"… makes it easy to react to user input …"

2023-06-28 14:29 UTC, ixxie commented
@grischaerbe I addressed all the issues, but sometimes in somewhat different ways you suggested. I also streamline some other text a bit to shorten it. Can you give it a read through again to see if you are good with all of it?

2023-06-28 20:21 UTC, grischaerbe commented
LGTM 🚀 Thank you so much!

2023-06-28 20:21 UTC, merged