Psuedo random scenery [hackathon]
threlte/threlte pull request #702
Opened 2023-10-22 01:43 UTC by DefinitelyMaybe

Hi all,

This is my submission for the hackathon but it's not quite fully finished yet. Thought I'd add it into the mix anyway.

Enjoy!

2023-10-26 17:05 UTC, ixxie requested changes
In addition to the other comments, I would like you to consider:

- [ ] Refactoring `Scene.svelte` files to reduce filesize: the scenes have become quite large, making it a bit hard to follow the file. Could you try and break some of the code out into separate files? I'm thinking the standard lighting / camera stuff can stay in Scene, and we seperate the rest to a `Pseudorandom.svelte` file.
- [ ] Rename examples to streamline them and fit the new text - perhaps something like `uniform-pseudorandom-scenery`, `poisson-psuedorandom-scenery` and `variable-poisson-pseudorandom-scenery`.

2023-10-26 17:05 UTC, ixxie commented on apps/docs/src/examples/geometry/psuedo-random-scenery/adjusted-sampling/poissonDiscSampling.ts
Rename to `sampling.ts`.

2023-10-26 22:50 UTC, DefinitelyMaybe commented
All very good suggestions! thank you!

2023-10-30 08:34 UTC, ixxie approved these changes

2023-10-30 08:35 UTC, ixxie commented
Looks Great to Me! Good work @DefinitelyMaybe!

2023-10-30 08:35 UTC, merged